"""
Entity types
"""

# Encodes genetic information.
abstract type Genotype end

# Generates a genotype.
abstract type GenotypeConfiguration end

# Transforms a genotype into a data structure
abstract type PhenotypeConfiguration end

# Evolutionary instantiations of a genotype
abstract type Individual end

# A collection of individuals. 
abstract type Species end

# Creates a species.
abstract type SpeciesConfiguration end

# A collection of species.
abstract type Ecosystem end

function get_pheno_dict(::Ecosystem)
    throw(ErrorException("Required metod `get_pheno_dict` not implemented for Ecosystem."))
end

# Creates an ecosystem.
abstract type EcosystemConfiguration end 

"""
Interaction types
"""

# Defines a task to be performed by a set of entities.
abstract type Problem end

# Chooses sets of entities to perform a task.
abstract type MatchMaker end

# Data produced by an interaction.
abstract type Observation end

# Specifies data to collect from an interaction.
abstract type ObservationConfiguration end


"""

    function interact(problem::Problem, domain_id::Int, obs_cfg::ObservationConfiguration, args...)

    Perform an interaction between entities and return the results.

"""
function interact(problem::Problem, domain_id::Int, obs_cfg::ObservationConfiguration, args...)
    throw(ErrorException("Required method `interact` not implemented for Problem."))
end

# Specifies an interactive domain.
abstract type DomainConfiguration end

# Evaluation work to be performed by a worker.
abstract type Job end 

# Specifies a set of jobs to be performed.
abstract type JobConfiguration end



"""
Genetic algorithm and reproduction types
"""

# Stores the evaluation information for an individual.
abstract type Evaluation end

abstract type EvaluationConfiguration end

# Replaces a population with a new generation.
abstract type Replacer end

# Selects parents from a population.
abstract type Selector end

# Generates children from the selected parents.
abstract type Recombiner end

# Mutates children.
abstract type Mutator end

"""
Analysis types
"""
# Logs and persists data generated by the coevolutionary process.
abstract type Archivist end 

abstract type ArchivistConfiguration end 

"""
Utility types
"""

# Whether we seek the minimum or maximum of a value for determining fitness.
abstract type Sense end
